version: '3'
services:
  ud-postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ud_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ud-vlan

  adminer:
    image: adminer:latest
    ports:
      - 8282:8080
    networks:
      - ud-vlan

volumes:
  postgres-data:

networks:
  ud-vlan:
    driver: bridge
